
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/cgulucan/.local/lib/python3.8/site-packages/cmake/data/share/cmake-4.0/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 5.15.167.4-microsoft-standard-WSL2 - x86_64
...
